version: '0.1'
services:
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    ports:
      - '1883:1883'
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
